[local]
localhost


[mongodb]
mongodb-dev.anildevops90.online

[catalogue]
catalogue-dev.anildevops90.online

[redis]
redis-dev.anildevops90.online

[user]
user-dev.anildevops90.online

[cart]
cart-dev.anildevops90.online

[mysql]
mysql-dev.anildevops90.online


[shipping]
shipping-dev.anildevops90.online

[rabbitmq]
rabbitmq-dev.anildevops90.online

[frontend]
frontend-dev.anildevops90.online

[payment]
payment-dev.anildevops90.online




MONGODB_HOST=mongodb-dev.anildevops90.online
CATALOGUE_HOST=catalogue-dev.anildevops90.online
REDIS_HOST=redis-dev.anildevops90.online
USER_HOST=user-dev.anildevops90.online
CART_HOST=cart-dev.anildevops90.online
MYSQL_HOST=mysql-dev.anildevops90.online
SHIPPING_HOST=shipping-dev.anildevops90.online
RABBITMQ_HOST=rabbitmq-dev.anildevops90.online
FRONTEND_HOST=frontend-dev.anildevops90.online
PAYMENT_HOST=-payment-dev.anildevops90.online